name: videoeditbot_app
description: Video Edit Bot App

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  flutter_statusbarcolor: ^0.2.3
  shared_preferences: ^0.5.12
  url_launcher: ^5.7.2
  share: ">=0.6.5+2 <2.0.0"
  flutter_downloader: ^1.5.1
  permission_handler: ^5.0.1+1
  path_provider: ^1.6.18
  video_player: '>=0.10.0 <2.0.0'
  flick_video_player: ^0.1.1
  sliding_up_panel: ^1.0.2
  uni_links: ^0.4.0
  flutter_platform_widgets: ^0.70.1
  cupertino_icons: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/launcher/launcher.png"
  image_path_ios: "assets/launcher/ios.png"
  adaptive_icon_background: "assets/launcher/back.png"
  adaptive_icon_foreground: "assets/launcher/front.png"

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: VebIcons
      fonts:
        - asset: assets/icons/VebIcons.ttf
