/// Flutter icons VebIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VebIcons
///      fonts:
///       - asset: fonts/VebIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class VebIcons {
  VebIcons._();

  static const _kFontFam = 'VebIcons';
  static const _kFontPkg = null;

  static const IconData discord = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData memory = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xf099, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
